### ISSUE TITLE
iPython for Windows

### ISSUE THREAD

**Issue by AdamK42** [vladov3000/EPEtutorials#5]
For the iPython notebook, it says to open your terminal and type `python` to get the iPython terminal. This doesn't work as there is no iPython in the git bash terminal for windows out of the box. Should we add instructions for windows users?

**Comment by AdamK42** [comment]
The solution is to make sure the windows git bash is using the windows default console window and to allow Anaconda to be added to the PATH environment variable. I got these instructions from [here](https://www.earthdatascience.org/workshops/setup-earth-analytics-python/setup-git-bash-conda/).

**Comment by vladov3000** [comment]
Yeah, also it should be python3 not python.

**Comment by AdamK42** [comment]
Typing just `python` gets me the python 3 iPython environment on both windows and linux. Are you sure?
